services:

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env

  frontend:
    build: ./FrontEnd
    ports:
      - "5173:80"
    depends_on:
      - backend